spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.xml
